### ISSUE TITLE
One PKGBUILD multiple packages fails installation

### ISSUE THREAD

**Issue by txomon** [gavinhungry/packer#11]
When you have a lot of AUR packages, there are some of them that create several packages from the same PKGBUILD, examples:
 * invoke
 * python-path
 * gstreamer0.10-base and gstreamer0.10-base-plugins

For some reason, packer fails to build them all.

**Comment by gavinhungry** [comment]
I think this is fixed by dc4201be451bb9df12e0fa1f1b27beeb38185ed5. I tried installing `invoke` and `python-path` (neither of which I had installed previously) - both installed fine.

If you're using the [packer-git](https://aur.archlinux.org/packages/packer-git/) package (which I don't manage), you can update with `packer -Syua --devel`, or just `packer -S packer-git` to get the latest Git revision.

**Comment by txomon** [comment]
The problem is with upgrades, not with installations. Sorry for not making
it clear enough.

About packer, I don't remember which is my version but I will update it now
and report back when I find a similar situation

**Comment by gavinhungry** [comment]
Closing, as I think this is fixed by dc4201be451bb9df12e0fa1f1b27beeb38185ed5.
