### ISSUE TITLE
aur4 support

### ISSUE THREAD

**Issue by jristz** [gavinhungry/packer#5]
With the upcoming and innevitable aur4 git comming it will be nice it could be possible that packer could use aur4 for download packages and handle that stuff.

Deadline july8, then aur and aur4 will switch and the old aur will be readonly and all will happend in aur 4.0.0

**Comment by gavinhungry** [comment]
Since not all of the packges on the AUR are yet on AUR4, I thought I might make this optional for now (via `--aur4`) and then remove that argument and make AUR4 the default (or only) option after the switch.

It seems bizarre to me though, that the AUR4 RPC search returns results for packages only in the old AUR (and not yet available on AUR4). That makes things very confusing.

**Comment by gavinhungry** [comment]
The more I think about it, I think I might make AUR4 the default.

**Comment by dumblob** [comment]
As a maintainer of the AUR/AUR4 *packer* PKGBUILD I was thinking about adding AUR4 support for this period until they fully switch to AUR4, but came to a conclusion, that only if some users will raise their hands, I'll ask you here.

Right now it seems, we [reached the point](https://aur4.archlinux.org/packages/packer-git/) and thus I advocate for temorarily adding the `--aur4` option (possibly with a message on the first line stating *"The --aur4 option will be removed after 8. 8. 2015."*).

**Comment by gavinhungry** [comment]
I'm just dumping the old AUR. This fork of packer will just use AUR4 (since a lot of the packages on the old AUR are already out of date, never to be updated again).

I realize that not all packages have been moved over to AUR4 yet, but continuing to support the old AUR it this close to The End isn't going to help that.

**Comment by gavinhungry** [comment]
I'll have a minor update when AUR4 changes domains to change `AUR_DOMAIN`.
